### ISSUE TITLE
Add totalEvents to /outages/summary endpoint

### ISSUE THREAD

**Issue by JayWebz** [CAIDA/ioda-api#38]
/v2/outages/summary/{entityType}/{entityCode} currently returns:
```
entity:
  attrs: {fqid: "geo.netacuity.AS.MM"}
  code: "MM"
  name: "Myanmar"
  type: "country"
  scores: {bgp: 30772.6618705036, ping-slash24: 10533.61344537815, overall: 323935157.07635576}
``` 
I'd like to see:
```
entity:
  attrs: {fqid: "geo.netacuity.AS.MM"}
  code: "MM"
  name: "Myanmar"
  type: "country"
  outageEvents: 3 (an INT that displays total number of events that occurred in the given time period)
  scores: {bgp: 30772.6618705036, ping-slash24: 10533.61344537815, overall: 323935157.07635576}
``` 

The reason for this is because on the dashboard page, I need a way to determine when the api calls for `/signals/events/` have completed since I am calling a signal endpoint for each entity listed. This will allow me to cross reference the number of events populated from the complete list provided in the `outages/summary` endpoint with the number of events that are populating from calling `signals/events` on each entity as they trickle in. Once The numbers match, I can populate the data to the visualization in one go.
